name: my_app
description: Annotations for Elements Generators
version: 0.1.0
publish_to: none

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  custom_generator:
    path: ../custom_generator
  custom_generator_annotations:
    path: ../custom_generator_annotations
  build_runner: ^2.2.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.21.1
