name: custom_generator
description: Dart Code Generator
version: 0.1.0
publish_to: none

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  analyzer: ">=3.0.0 <5.0.0"
  build: ^2.1.0
  source_gen: ^1.2.2
  build_config: ^1.0.0
  custom_generator_annotations:
    path: ../custom_generator_annotations

dev_dependencies:
  lints: ^1.0.0
  test: ^1.21.1
  build_runner: ^2.1.10
